require File.dirname(__FILE__) + '/rubizon/security_credentials'
require File.dirname(__FILE__) + '/rubizon/workers'
require File.dirname(__FILE__) + '/rubizon/xml_reader'
require File.dirname(__FILE__) + '/rubizon/request'
require File.dirname(__FILE__) + '/rubizon/results'
require File.dirname(__FILE__) + '/rubizon/default_responder'
require File.dirname(__FILE__) + '/rubizon/exceptions'
require File.dirname(__FILE__) + '/rubizon/status_and_body'
module Rubizon
  autoload :Version, File.dirname(__FILE__) + '/rubizon/version'
  autoload :AbstractSig2Product, File.dirname(__FILE__) + '/rubizon/abstract_sig2_product'
  autoload :ProductAdvertisingProduct, File.dirname(__FILE__) + '/rubizon/product/product_advertising'
  autoload :SimpleNotificationService, File.dirname(__FILE__) + '/rubizon/product/sns'
  autoload :SimpleDBService, File.dirname(__FILE__) + '/rubizon/product/sdb'
end
